services:
  - type: web
    name: konquis-backend
    env: node
    plan: free
    # Indica que la raíz del servicio es la carpeta backend dentro del repo
    rootDirectory: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
